---
- name: Set up groups
  group:
    name:   "{{ item.name }}"
    gid:    "{{ item.gid | default(omit) }}"
    state:  "{{ item.state }}"
    system: "{{ item.system | default(omit) }}"
  with_items: group_list
  tags:
    - environment
    - groups
