---
- name: Install system vimrc.local
  copy:
    src:  "vimrc.local"
    dest: "/etc/vim/vimrc.local"
  when: ansible_os_family == "Debian"

- name: Make vim the default editor
  alternatives:
    name: "editor"
    path: "/usr/bin/vim.basic"
  when: ansible_os_family == "Debian"

- name: Install system vimrc.local
  copy:
    src:  "vimrc.local"
    dest: "/etc/vimrc.local"
  when: ansible_os_family == "RedHat"

- name: Make vimrc read vimrc.local
  lineinfile:
    dest: "/etc/vimrc"
    line: "source /etc/vimrc.local"
  when: ansible_os_family == "RedHat"
