---
- hosts: elastic1
  remote_user: vagrant
  sudo: true
  sudo_user: root
  tasks:
    - name: log in as vagrant
      shell: whoami
    - name: ensure ntpd is at the latest version
      apt: pkg=ntp state=latest
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted

